services:
  cutstock:
    image: git.rohde.one/oliver/cutstock:latest
    container_name: cutstock
    restart: unless-stopped
    ports:
      - "8420:8000"
    volumes:
      - /mnt/user/appdata/cutstock:/data
    environment:
      - CUTSTOCK_DB=/data/cutstock.db
